//! Linux policy routing, table 51820 management, subnet NAT, and exit-node killswitch engine.

use ipnet::Ipv4Net;
use std::{net::Ipv4Addr, process::Command};
use tracing::{debug, error, info, warn};

/// Default routing table ID for oxide overlay routing (standard WireGuard/Tailscale convention)
pub const DEFAULT_ROUTING_TABLE: u32 = 51820;
/// Default firewall mark to prevent routing loops for packets generated by the daemon itself
pub const DEFAULT_FWMARK: u32 = 0x51820;

/// Policy routing configuration
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PolicyRoutingConfig {
    pub table_id: u32,
    pub fwmark: u32,
    pub tun_interface: String,
    pub overlay_ip: Ipv4Addr,
    pub allow_lan_access: bool,
    pub dry_run: bool,
}

impl Default for PolicyRoutingConfig {
    fn default() -> Self {
        Self {
            table_id: DEFAULT_ROUTING_TABLE,
            fwmark: DEFAULT_FWMARK,
            tun_interface: "oxide0".to_string(),
            overlay_ip: Ipv4Addr::new(100, 64, 0, 1),
            allow_lan_access: true,
            dry_run: false,
        }
    }
}

/// Linux policy routing and firewall manager
pub struct PolicyRoutingManager {
    config: PolicyRoutingConfig,
    active_exit_node: Option<Ipv4Addr>,
    active_masqueraded_subnets: Vec<(Ipv4Net, String)>,
    applied_rules: Vec<String>,
}

impl PolicyRoutingManager {
    pub fn new(config: PolicyRoutingConfig) -> Self {
        Self {
            config,
            active_exit_node: None,
            active_masqueraded_subnets: Vec::new(),
            applied_rules: Vec::new(),
        }
    }

    /// Enable IPv4 packet forwarding in the kernel (`net.ipv4.ip_forward=1`)
    pub fn enable_ip_forwarding(&self) -> Result<(), String> {
        info!("Enabling kernel IPv4 forwarding (net.ipv4.ip_forward=1)...");
        if self.config.dry_run {
            debug!("[DRY-RUN] sysctl -w net.ipv4.ip_forward=1");
            return Ok(());
        }

        let output = Command::new("sysctl")
            .args(["-w", "net.ipv4.ip_forward=1"])
            .output()
            .map_err(|e| format!("Failed to execute sysctl: {}", e))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            warn!("sysctl warning/error: {}", stderr);
        }
        Ok(())
    }

    /// Setup policy routing rules (`ip rule add not fwmark ... table ...`)
    pub fn setup_policy_rules(&mut self) -> Result<(), String> {
        info!(
            "Setting up Linux policy routing rules for table {} and fwmark {:#x}...",
            self.config.table_id, self.config.fwmark
        );

        let table_str = self.config.table_id.to_string();
        let fwmark_str = format!("{:#x}", self.config.fwmark);

        // Rule 1: Not fwmark -> lookup table 51820
        let rule1_args = vec![
            "rule", "add", "not", "fwmark", &fwmark_str, "table", &table_str,
        ];
        self.exec_ip(&rule1_args)?;
        self.applied_rules.push(format!("not fwmark {} table {}", fwmark_str, table_str));

        // Rule 2: Suppress default prefix in main table to prevent routing blackholes
        let rule2_args = vec![
            "rule", "add", "table", "main", "suppress_prefixlength", "0",
        ];
        self.exec_ip(&rule2_args)?;
        self.applied_rules.push("table main suppress_prefixlength 0".to_string());

        Ok(())
    }

    /// Teardown policy routing rules
    pub fn teardown_policy_rules(&mut self) -> Result<(), String> {
        info!("Tearing down Linux policy routing rules...");
        let table_str = self.config.table_id.to_string();
        let fwmark_str = format!("{:#x}", self.config.fwmark);

        // Delete rule 1
        let _ = self.exec_ip(&[
            "rule", "del", "not", "fwmark", &fwmark_str, "table", &table_str,
        ]);

        // Delete rule 2
        let _ = self.exec_ip(&[
            "rule", "del", "table", "main", "suppress_prefixlength", "0",
        ]);

        // Flush routing table
        let _ = self.exec_ip(&["route", "flush", "table", &table_str]);

        self.applied_rules.clear();
        Ok(())
    }

    /// Configure Exit-Node default route routing through the overlay tunnel
    pub fn enable_exit_node(&mut self, exit_node_ip: Ipv4Addr) -> Result<(), String> {
        info!(
            "Enabling Exit-Node routing via peer {} on interface {}...",
            exit_node_ip, self.config.tun_interface
        );
        let table_str = self.config.table_id.to_string();

        // 1. Add default route in table 51820 to the TUN interface
        self.exec_ip(&[
            "route",
            "replace",
            "default",
            "dev",
            &self.config.tun_interface,
            "table",
            &table_str,
        ])?;

        // 2. If allow_lan_access is enabled, add bypass routes for private IPv4 ranges to table 51820
        if self.config.allow_lan_access {
            debug!("Configuring LAN bypass exceptions for exit node...");
            let lan_subnets = ["192.168.0.0/16", "10.0.0.0/8", "172.16.0.0/12"];
            for subnet in &lan_subnets {
                let _ = self.exec_ip(&[
                    "route", "replace", subnet, "scope", "link", "table", &table_str,
                ]);
            }
        }

        self.active_exit_node = Some(exit_node_ip);
        Ok(())
    }

    /// Disable Exit-Node default route routing
    pub fn disable_exit_node(&mut self) -> Result<(), String> {
        info!("Disabling Exit-Node routing...");
        let table_str = self.config.table_id.to_string();
        let _ = self.exec_ip(&["route", "del", "default", "table", &table_str]);
        self.active_exit_node = None;
        Ok(())
    }

    /// Setup Subnet Router NAT masquerade (`iptables -t nat -A POSTROUTING ...`)
    pub fn setup_subnet_masquerade(
        &mut self,
        subnet: Ipv4Net,
        egress_interface: &str,
    ) -> Result<(), String> {
        info!(
            "Setting up NAT masquerading for advertised subnet {} on egress interface {}...",
            subnet, egress_interface
        );
        self.enable_ip_forwarding()?;

        let subnet_str = subnet.to_string();
        self.exec_iptables(&[
            "-t",
            "nat",
            "-A",
            "POSTROUTING",
            "-s",
            &subnet_str,
            "-o",
            egress_interface,
            "-j",
            "MASQUERADE",
        ])?;

        self.active_masqueraded_subnets
            .push((subnet, egress_interface.to_string()));
        Ok(())
    }

    /// Teardown Subnet Router NAT masquerade
    pub fn teardown_subnet_masquerade(
        &mut self,
        subnet: Ipv4Net,
        egress_interface: &str,
    ) -> Result<(), String> {
        info!(
            "Tearing down NAT masquerading for subnet {} on interface {}...",
            subnet, egress_interface
        );
        let subnet_str = subnet.to_string();
        let _ = self.exec_iptables(&[
            "-t",
            "nat",
            "-D",
            "POSTROUTING",
            "-s",
            &subnet_str,
            "-o",
            egress_interface,
            "-j",
            "MASQUERADE",
        ]);

        self.active_masqueraded_subnets
            .retain(|(s, iface)| !(*s == subnet && iface == egress_interface));
        Ok(())
    }

    /// Helper to execute `ip` command safely
    fn exec_ip(&self, args: &[&str]) -> Result<(), String> {
        if self.config.dry_run {
            debug!("[DRY-RUN] ip {}", args.join(" "));
            return Ok(());
        }

        let output = Command::new("ip")
            .args(args)
            .output()
            .map_err(|e| format!("Failed to execute 'ip {}': {}", args.join(" "), e))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            // Ignore "File exists" if rule already added
            if !stderr.contains("File exists") && !stderr.contains("No such file or directory") {
                error!("Command 'ip {}' failed: {}", args.join(" "), stderr);
                return Err(format!("'ip {}' failed: {}", args.join(" "), stderr));
            }
        }
        Ok(())
    }

    /// Helper to execute `iptables` command safely
    fn exec_iptables(&self, args: &[&str]) -> Result<(), String> {
        if self.config.dry_run {
            debug!("[DRY-RUN] iptables {}", args.join(" "));
            return Ok(());
        }

        let output = Command::new("iptables")
            .args(args)
            .output()
            .map_err(|e| format!("Failed to execute 'iptables {}': {}", args.join(" "), e))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            error!("Command 'iptables {}' failed: {}", args.join(" "), stderr);
            return Err(format!("'iptables {}' failed: {}", args.join(" "), stderr));
        }
        Ok(())
    }

    pub fn active_exit_node(&self) -> Option<Ipv4Addr> {
        self.active_exit_node
    }

    pub fn applied_rules_count(&self) -> usize {
        self.applied_rules.len()
    }
}

impl Drop for PolicyRoutingManager {
    fn drop(&mut self) {
        if !self.applied_rules.is_empty() || !self.active_masqueraded_subnets.is_empty() {
            debug!("PolicyRoutingManager dropping: cleaning up rules and routes...");
            while let Some((subnet, iface)) = self.active_masqueraded_subnets.pop() {
                let _ = self.teardown_subnet_masquerade(subnet, &iface);
            }
            let _ = self.teardown_policy_rules();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;

    #[test]
    fn test_policy_routing_manager_dry_run_lifecycle() {
        let config = PolicyRoutingConfig {
            table_id: 51820,
            fwmark: 0x51820,
            tun_interface: "oxide-test0".to_string(),
            overlay_ip: Ipv4Addr::new(100, 64, 0, 42),
            allow_lan_access: true,
            dry_run: true,
        };

        let mut mgr = PolicyRoutingManager::new(config);
        assert_eq!(mgr.applied_rules_count(), 0);

        // Setup rules
        assert!(mgr.setup_policy_rules().is_ok());
        assert_eq!(mgr.applied_rules_count(), 2);

        // Enable exit node
        let exit_ip = Ipv4Addr::new(100, 64, 0, 1);
        assert!(mgr.enable_exit_node(exit_ip).is_ok());
        assert_eq!(mgr.active_exit_node(), Some(exit_ip));

        // Subnet masquerading
        let subnet = Ipv4Net::from_str("192.168.10.0/24").unwrap();
        assert!(mgr.setup_subnet_masquerade(subnet, "eth0").is_ok());
        assert_eq!(mgr.active_masqueraded_subnets.len(), 1);

        // Teardown
        assert!(mgr.disable_exit_node().is_ok());
        assert_eq!(mgr.active_exit_node(), None);

        assert!(mgr.teardown_subnet_masquerade(subnet, "eth0").is_ok());
        assert_eq!(mgr.active_masqueraded_subnets.len(), 0);

        assert!(mgr.teardown_policy_rules().is_ok());
        assert_eq!(mgr.applied_rules_count(), 0);
    }
}
