//! Atomic /etc/resolv.conf backup, rewrite, and restoration manager

use std::{fs, path::PathBuf};
use tracing::{debug, error, info};

/// ResolvConf manager configuration
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvConfConfig {
    pub resolv_path: PathBuf,
    pub backup_path: PathBuf,
    pub nameservers: Vec<String>,
    pub search_domains: Vec<String>,
    pub dry_run: bool,
}

impl Default for ResolvConfConfig {
    fn default() -> Self {
        Self {
            resolv_path: PathBuf::from("/etc/resolv.conf"),
            backup_path: PathBuf::from("/etc/resolv.conf.oxide-backup"),
            nameservers: vec!["100.100.100.100".to_string()],
            search_domains: vec!["mesh.oxide".to_string(), "oxide".to_string()],
            dry_run: false,
        }
    }
}

/// ResolvConf manager for direct OS DNS configuration
pub struct ResolvConfManager {
    config: ResolvConfConfig,
    backup_created: bool,
}

impl ResolvConfManager {
    pub fn new(config: ResolvConfConfig) -> Self {
        Self {
            config,
            backup_created: false,
        }
    }

    /// Backup original resolv.conf and write new nameserver settings
    pub fn apply(&mut self) -> Result<(), String> {
        info!(
            "Applying direct resolv.conf configuration at {:?}...",
            self.config.resolv_path
        );

        if self.config.dry_run {
            debug!("[DRY-RUN] Backup {:?} -> {:?}", self.config.resolv_path, self.config.backup_path);
            debug!("[DRY-RUN] Write {:?} with nameservers {:?}", self.config.resolv_path, self.config.nameservers);
            self.backup_created = true;
            return Ok(());
        }

        // 1. Create backup if file exists and no backup exists yet
        if self.config.resolv_path.exists() && !self.config.backup_path.exists() {
            fs::copy(&self.config.resolv_path, &self.config.backup_path)
                .map_err(|e| format!("Failed to backup resolv.conf: {}", e))?;
            self.backup_created = true;
        }

        // 2. Generate new contents
        let mut contents = String::from("# Generated by oxide-mesh-net MagicDNS (Do not edit directly)\n");
        for ns in &self.config.nameservers {
            contents.push_str(&format!("nameserver {}\n", ns));
        }
        if !self.config.search_domains.is_empty() {
            contents.push_str(&format!("search {}\n", self.config.search_domains.join(" ")));
        }
        contents.push_str("options ndots:1 timeout:2 attempts:2\n");

        // 3. Write atomically via temp file
        let temp_path = self.config.resolv_path.with_extension("tmp");
        fs::write(&temp_path, contents)
            .map_err(|e| format!("Failed to write temporary resolv.conf: {}", e))?;

        fs::rename(&temp_path, &self.config.resolv_path)
            .map_err(|e| format!("Failed to atomically replace resolv.conf: {}", e))?;

        Ok(())
    }

    /// Restore original resolv.conf from backup
    pub fn restore(&mut self) -> Result<(), String> {
        if !self.backup_created {
            return Ok(());
        }

        info!("Restoring original resolv.conf from backup at {:?}...", self.config.backup_path);
        if self.config.dry_run {
            debug!("[DRY-RUN] Restore {:?} -> {:?}", self.config.backup_path, self.config.resolv_path);
            self.backup_created = false;
            return Ok(());
        }

        if self.config.backup_path.exists() {
            if let Err(e) = fs::rename(&self.config.backup_path, &self.config.resolv_path) {
                error!("Failed to restore resolv.conf backup: {}", e);
                return Err(format!("Failed to restore resolv.conf: {}", e));
            }
        }

        self.backup_created = false;
        Ok(())
    }

    pub fn backup_exists(&self) -> bool {
        self.backup_created
    }
}

impl Drop for ResolvConfManager {
    fn drop(&mut self) {
        if self.backup_created {
            let _ = self.restore();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_resolv_conf_manager_dry_run() {
        let config = ResolvConfConfig {
            resolv_path: PathBuf::from("/tmp/test-resolv.conf"),
            backup_path: PathBuf::from("/tmp/test-resolv.conf.bak"),
            nameservers: vec!["100.100.100.100".to_string()],
            search_domains: vec!["mesh.oxide".to_string()],
            dry_run: true,
        };

        let mut mgr = ResolvConfManager::new(config);
        assert!(!mgr.backup_exists());

        assert!(mgr.apply().is_ok());
        assert!(mgr.backup_exists());

        assert!(mgr.restore().is_ok());
        assert!(!mgr.backup_exists());
    }
}
